// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyrpdxnrijcxpctpohhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cnBkeG5yaWpjeHBjdHBvaGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTE3NTUsImV4cCI6MjA2NjUyNzc1NX0.wmO6G9ptlUitOCeqcpPp55ehxexNdTBjwBPyjb3R81Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});